### ISSUE TITLE
您这个模型的基座模型是哪个？

### ISSUE THREAD

**Issue by sun1092469590** [CrazyBoyM/llama2-Chinese-chat#3]
请问下，您使用llama-2的哪个基座模型训练的？llama-2-13b-chat-hf吗？当前开源的模型只有指令微调是吗？

**Comment by sun1092469590** [comment]
> 请问下，您使用llama-2的哪个基座模型训练的？llama-2-13b-chat-hf吗？当前开源的模型只有指令微调是吗？

哦哦，重读了一下read，不是用原始的llama-2，用了https://huggingface.co/TheBloke/Llama-2-13B-fp16作为基座模型

**Comment by CrazyBoyM** [comment]
是LLaMA2 13B，做的中文训练
