### ISSUE TITLE
在A100上测试了下效果一般

### ISSUE THREAD

**Issue by goog** [CrazyBoyM/llama2-Chinese-chat#4]
https://gist.github.com/goog/a3276016bd17eb401d6cc74d1f96d2e0

**Comment by goog** [comment]
请问lora模型都上GB了 是不是应该考虑中文基座？

**Comment by CrazyBoyM** [comment]
hh，您测试的例子是epoch1的嘛还是epoch2，因为我只有3张a800，没办法做大规模的增量训练。可以关注一下社区有一些给llama2扩词表的工作（顺便一提，最近的Qwen看着也很不错。

**Comment by goog** [comment]
我clone的 https://huggingface.co/shareAI/llama2-13b-Chinese-chat  
然后参考文档合的模型
请问3张a800微调一次大概多久呢

**Comment by CrazyBoyM** [comment]
数据量小的话跑十个小时，第二个epoch用了100k+跑了大概2天左右&nbsp;


---原始邮件---
发件人: &quot;Jay ***@***.***&gt;
发送时间: 2023年8月7日(周一) 中午11:21
收件人: ***@***.***&gt;;
抄送: &quot;Ke ***@***.******@***.***&gt;;
主题: Re: [CrazyBoyM/llama2-Chinese-chat] 在A100上测试了下效果一般 (Issue #4)




 
我clone的 https://huggingface.co/shareAI/llama2-13b-Chinese-chat
 然后参考文档合的模型
 请问3张a800微调一次大概多久呢
 
&mdash;

**Comment by goog** [comment]
有个问题想请教下 lora模型合不合到base model 对推理有没有影响？

**Comment by CrazyBoyM** [comment]
不合并也可以的，参考peft&nbsp;


---原始邮件---
发件人: &quot;Jay ***@***.***&gt;
发送时间: 2023年8月7日(周一) 中午11:29
收件人: ***@***.***&gt;;
抄送: &quot;Ke ***@***.******@***.***&gt;;
主题: Re: [CrazyBoyM/llama2-Chinese-chat] 在A100上测试了下效果一般 (Issue #4)




 
有个问题想请教下 lora模型合不合到base model 对推理有没有影响？
 
&mdash;
